### PR TITLE
Apply changes to fix incompatibility with newest HA 2024.1.3 (see: #80)

### PR DESCRIPTION
**Pull request by RAYs3T**
from: https://github.com/Danielhiversen/home_assistant_tibber_data/issues/80#issuecomment-1890408402

### CODE REVIEW

**Comment by newlund** [comment]
I have tried to apply this patch. Solved the problem for me. Thanks! :)

**Comment by Danielhiversen** [comment]
Seems to be more breaking changes in latest HA, I can look into it later:
https://github.com/Danielhiversen/home_assistant_tibber_data/actions/runs/7518973818/job/20580509999?pr=81

**Comment by FSHelgeland** [comment]
I guess there eventually will be a fix, but if I want to update now. Then what do I have to do in order to still keep Tibber Data alive?

**Comment by RAYs3T** [comment]
> I guess there eventually will be a fix, but if I want to update now. Then what do I have to do in order to still keep Tibber Data alive?

You need to manually adjust the lines in the addon code running on your home assistant server. Use an editor or visual studio code (addon) and adjust the lines in the two files as seen in this PR. A full restart of HA is required afterwards.

**Comment by LarsTh86** [comment]
which lines?

**Comment by RAYs3T** [comment]
> which lines?

1. Go to addons
2. Install Studio Code Server
3. Open Studio Code Server
4. Locate the folder "custom_components/tibber_data"
5. Open the file `sensor.py` and replace the contents with: https://raw.githubusercontent.com/Danielhiversen/home_assistant_tibber_data/3fc733f2b13da67e2e3878a35989a5fdb26ca96f/custom_components/tibber_data/sensor.py
6. Open `binary_sensor.py` and replace the contents with: https://raw.githubusercontent.com/Danielhiversen/home_assistant_tibber_data/3fc733f2b13da67e2e3878a35989a5fdb26ca96f/custom_components/tibber_data/binary_sensor.py
7. Save the files and restart HomeAssistant
image

**Pull request merged**
